In [25]:
#1
import numpy as np
arr=np.array({1,2,3})
print(arr)

{1, 2, 3}


In [26]:
#2
import numpy as np
arr=np.arange(30).reshape(6,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [27]:
#3
import numpy as np
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
#3
import numpy as np
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
#4
# create full function with 2D filled of 7
import numpy as np
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [30]:
#5
#impliment slicing
import numpy as np
arr = np.arange(64).reshape(8,8)
#Prt 1
print(arr[:,:])
#Prt 2
print(arr[2:5, 0:3])
#Prt 3
print(arr[0:2, 0:5])
#Prt 4
print(arr[2:4, 2:4])
#Prt 5
print(arr[-3:-1, -3:-1])
#Prt 6
print(arr[-4:-1, -4:-1])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[[16 17 18]
 [24 25 26]
 [32 33 34]]
[[ 0  1  2  3  4]
 [ 8  9 10 11 12]]
[[18 19]
 [26 27]]
[[45 46]
 [53 54]]
[[36 37 38]
 [44 45 46]
 [52 53 54]]


In [31]:
#6 
#Impliment to find out dimension
import numpy as np
arr = np.array([1, 2, 3, 4])
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)

1
2
3


In [32]:
#7
#Create 8D Array with value [2, 2, 2, 2]
import numpy as np
arr = np.array([2, 2, 2, 2], ndmin = 8)
print(arr)

[[[[[[[[2 2 2 2]]]]]]]]
